Allow docker compose to set port
getmoto/moto pull request #6181
Opened 2023-04-06 05:47 UTC by deepakmeena635

Hi there, 

Currently, I'm deploying a moto container with other aws and localstack containers as others don't support athena.
It's being done with a docker-compose file which makes it easily manageable. But the problem is on some of my teams machines port 5000 is blocked by os and the process respawns when killed.

It'd be awesome if we can allow the port to be configured in the dockerfile. if there are other solutions that allow it to be done via docker compose I'll be more than happy to implement them.

2023-04-06 09:53 UTC, bblommers commented
Hi @deepakmeena635, the server-script already has a `MOTO_PORT` environment variable that you can use:

https://github.com/getmoto/moto/blob/bbb07b4e7ede832d69b8fe0089e0707c915710fc/moto/server.py#L41

Does that fix your problem?

2023-04-06 12:54 UTC, deepakmeena635 commented
thanks @bblommers, it solves my problem is there any documentation that i can update for anyone else wondering about this

2023-04-09 15:47 UTC, mikegrima commented
Is this ready to merge?

2023-04-10 11:58 UTC, deepakmeena635 commented
Thanks @bblommers and @mikegrima done from my side

2023-04-10 12:05 UTC, bblommers requested changes

2023-04-10 12:05 UTC, bblommers commented on Dockerfile
The changes in this file are not necessary, right?

2023-04-10 12:09 UTC, deepakmeena635 commented on Dockerfile
yes one second

2023-04-10 12:10 UTC, deepakmeena635 commented on Dockerfile
done, thanks for pointing it out

2023-04-10 12:11 UTC, deepakmeena635 commented
wait

2023-04-10 12:12 UTC, deepakmeena635 commented on Dockerfile
done now

2023-04-10 15:44 UTC, bblommers approved these changes
Awesome, thanks for adding this @deepakmeena635!

2023-04-10 15:45 UTC, merged