fix/describe-target-health: expected results when target is not registered
getmoto/moto pull request #6195
Opened 2023-04-10 05:41 UTC by mtulio

## Issue:

describe-target-health is not returning the expected structure when the target is new

## Steps to reproduce:

- create the target group (without registering the target)
- send describe-target-health with a target as a parameter

## Current results:

```
botocore.errorfactory.InvalidTargetException: An error occurred (InvalidTarget) when calling the DescribeTargetHealth operation: The specified target does not exist or is not in the same VPC as the target group.
```

## Expected results

```
Valid `FakeHealthStatus`  with reason `Target.NotRegistered`
```

## References

- https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_TargetHealth.html
-

2023-04-10 06:46 UTC, mtulio commented on moto/elbv2/models.py
> +                "unavailable",
I am not sure about the status value, I assumed it for the desired `Reason=Target.NotRegistered`

2023-04-10 15:47 UTC, bblommers requested changes
Looks like our linter is failing atm.

Would be good to have a test for this as well - I don't think this scenario is covered yet in our tests

2023-04-15 17:28 UTC, mtulio commented
> Looks like our linter is failing atm.
> 
> Would be good to have a test for this as well - I don't think this scenario is covered yet in our tests

Hey @bblommers , linter fixed and unit added. LMK WDYT. Thanks

2023-04-17 16:42 UTC, bblommers approved these changes
LGTM - thanks again @mtulio!

2023-04-17 16:43 UTC, merged