Add metrics to moto responses for ec2 target tracking scaling
getmoto/moto pull request #6314
Opened 2023-05-11 09:20 UTC by Ivan-Lukianov

## Purpose

AWS recently added support of metric math for target tracking scaling and changed scheme by adding new field `Metrics` to `CustomizedMetricSpecification`.

AWS blog announcement - https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-ec2-auto-scaling-supports-metric-math-target-tracking-policies/

This PR adds `Metrics` to moto responses for ec2 target tracking scaling.

2023-05-11 10:28 UTC, bblommers requested changes
Hi @Ivan-Lukianov, it would be good to have some unit test coverage for this.

There already is an existing test that covers target tracking, `tests/test_autoscaling/test_autoscaling.py::test_create_autoscaling_policy_with_policytype__targettrackingscaling` - we can extend that to also cover these `Metrics`.

2023-05-11 11:43 UTC, Ivan-Lukianov commented
@bblommers  thank you for looking into this!

Extended existing test to check `Metrics`, also during writing a test found a bug with ReturnData, fixed that as well.

2023-05-12 17:03 UTC, Ivan-Lukianov commented
Fixed indent in test_autoscaling.py

2023-05-13 17:07 UTC, bblommers approved these changes
LGTM. Thank you for adding this feature @Ivan-Lukianov, and welcome to Moto!

2023-05-13 17:08 UTC, merged