add support for ssm maintenance window task
getmoto/moto pull request #6430
Opened 2023-06-21 17:11 UTC by pinzon

This PR adds support for some operations related to Maintenance Window Tasks:

- [ ] register_task_with_maintenance_window
- [ ] describe_maintenance_window_tasks
- [ ] deregister_task_from_maintenance_window

2023-06-22 17:16 UTC, mikegrima commented
Codecov complains that there are 2 spots not covered by tests. Mostly a nitpick, but we would prefer you have coverage for it.

2023-06-27 21:18 UTC, bblommers requested changes

2023-06-27 21:18 UTC, bblommers commented on moto/ssm/models.py
> +import uuid
This should use the `mock_random` as well

2023-06-27 21:18 UTC, bblommers commented on tests/test_ssm/test_ssm_maintenance_windows.py
> +def test_describe_maintenance_window_with_no_task_or_targets():
Looks like this is missing the `mock_ssm`-decorator

2023-06-28 21:29 UTC, bblommers approved these changes
Awesome - thanks @pinzon!

2023-06-28 21:30 UTC, merged