feat(lambda): create list aliases functionality
getmoto/moto pull request #6455
Opened 2023-06-28 15:27 UTC by freshollie

- Creates the [list_aliases](https://boto3.amazonaws.com/v1/documentation/api/1.26.85/reference/services/lambda/client/list_aliases.html) functionality
- Redesign internal storage of aliases to correct mistaken implementation (The same alias name could be created under the same lambda pointing to different versions)
- Adds tests for new functionality

2023-06-28 15:32 UTC, freshollie commented
Let me know if you want docs updated as part of this PR

2023-06-28 15:34 UTC, freshollie commented on moto/awslambda/models.py
> -    def delete_alias(self, name: str) -> None:
Moved the logic to lambda storage level

2023-06-28 15:36 UTC, freshollie commented on moto/awslambda/models.py
> +        self._aliases: Dict[str, Dict[str, LambdaAlias]] = defaultdict(lambda: {})
Aliases are associated with the "lambda" not the "lambda version". We can't store these in "lambda version" as it makes it very complex to check if the alias already exists before writing. It also simplifies fetching a list of aliases as we don't need to iterate over each "version" to find it's alias

2023-06-29 08:46 UTC, freshollie commented
Will look into the failing test

2023-07-01 10:31 UTC, bblommers requested changes
This looks really good. Thank you for this PR @freshollie!

To show our thanks, we'd like to share some of the donations that we've received with you. PR's like this are the big reason that Moto is as successful as it is - so it's only fair that you, as a contributor, get to share the spoils.

We've created a companion website with more information:
https://payments.getmoto.org/

This website is still in beta, but everything should work. Feel free to open a bug or discussion if you run into any problems:
https://github.com/getmoto/payments

2023-07-01 10:32 UTC, merged