Add ECR support to lambda `update_function_code()`
getmoto/moto pull request #6586
Opened 2023-08-01 16:59 UTC by rbailey-godaddy

This apparently got missed, resulting in a null operation when this method was called for an ECR-based lambda.

This fix roughly clones the missing code from `create_function()` and adjusts the parameter name.

Fixes #6584

2023-08-01 21:53 UTC, bblommers requested changes
Would you mind adding a test for this @rbailey-godaddy?

There is quite a bit of duplication going on now between `create` and `update`, and I'm happy to tackle that at a later stage - but having tests to verify that we're not going to break this (again) is always useful.

2023-08-02 00:20 UTC, rbailey-godaddy commented
> Would you mind adding a test for this @rbailey-godaddy?

Sure thing -- I'm OOO for the remainder of this week, but I'll pick it up again next week.

2023-08-07 16:44 UTC, rbailey-godaddy commented
@bblommers -- I have consolidated the logic for both functions into a single helper, although it is weirder than I hope it should be in order to preserve existing behavior examined by existing unit tests. I also added a new unit test for the "update ECR" case, and revised the PR description to better reflect what is going on.

2023-08-08 10:11 UTC, bblommers approved these changes
LGTM - thanks for fixing this @rbailey-godaddy!

2023-08-08 10:11 UTC, merged