Feature: s3 sns notification
getmoto/moto pull request #6838
Opened 2023-09-20 22:27 UTC by maederm

Implement missing s3 sns notifications.

- [x] Feature is added
- [ ] The linter is happy
- [ ] Tests are added
- [ ] All tests pass, existing and new

I created a new test file because I couldn't find any tests that test the notifications themselves (the ones in test_s3.py test the configuration options, but not the implementation of send_event).
I'm not sure if need to update the function docs from models.py and the s3.rst, just edited both to be sure.

2023-09-21 07:32 UTC, maederm commented
I'm not sure what my changes have to do with terraform failing.

```
=== CONT  TestAccAPIGatewayV2Authorizer_HTTPAPILambdaRequestAuthorizer_initialMissingCacheTTL
=== NAME  TestAccAPIGatewayV2Authorizer_HTTPAPILambdaRequestAuthorizer_initialZeroCacheTTL
    testing_new.go:88: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: waiting for EC2 VPC (vpc-7ffe1a55) delete: operation error EC2: DescribeVpcs, https response error StatusCode: 400, RequestID: , decomposing response: read tcp [::1]:50438->[::1]:4566: use of closed network connection

```

2023-09-21 18:03 UTC, bblommers requested changes
Hi @maederm, thanks for the PR! The logic looks good to me.

Can you move the test case into `test_s3/test_s3_lambda_integration`? The name is a misnomer, but that file contains all other bucket notification tests

2023-09-21 18:04 UTC, bblommers commented
> I'm not sure what my changes have to do with terraform failing.
> 

Probably a intermittent failure - don't worry about that.

2023-09-22 13:16 UTC, bblommers approved these changes
LGTM - thank you @maederm!

2023-09-22 13:17 UTC, merged