SecretsManager: Add BatchGetValue implementation
getmoto/moto pull request #7519
Opened 2024-03-25 04:21 UTC by hpaskalev

Hi all, I've been working on some stuff these days and stumbled upon this [issue](https://github.com/localstack/localstack/issues/9982) on the LocalStack board. 
So, I decided to contribute by providing an implementation for the batch_get_secret_value feature.

2024-03-31 12:37 UTC, hpaskalev commented
The missing tests codecov was complaining about should be now in place.

2024-04-01 20:06 UTC, bblommers requested changes
Hi @hpaskalev, thank you for the PR! Please see my comments

2024-04-01 20:06 UTC, bblommers commented on tests/test_secretsmanager/test_secretsmanager.py
> +    matched = [
This has the potential to hide some problems - `secrets_batch` could (somehow) contain other secrets that are filtered out in this list.

```suggestion
    assert len(secret_batch["SecretValues"]) == 2
```
This achieves the same thing, as far as I can see.

2024-04-01 20:06 UTC, bblommers commented on tests/test_secretsmanager/test_secretsmanager.py
> +    matched = [
Same here with the matching.

Alternative:
```
assert [sec["ARN"] for sec in secrets_batch["SecretValues"]] == [secret_a["ARN"], secret_b["ARN"]]
```

2024-04-01 20:06 UTC, bblommers commented on tests/test_secretsmanager/test_secretsmanager.py
> +        err = exc.value.response["Error"]
This part is never reached. The `batch_get_secret_value` throws an error, and pytest will ignore any other code within this context manager.

It should be unindented, so it is executed after the context manager finishes:
```suggestion
    err = exc.value.response["Error"]
```

2024-04-01 20:06 UTC, bblommers commented on tests/test_secretsmanager/test_secretsmanager.py
> +        err = exc.value.response["Error"]
Same un-indentation here

2024-04-01 20:06 UTC, bblommers commented on tests/test_secretsmanager/test_secretsmanager.py
> +        err = exc.value.response["Error"]
Same un-indentation here

2024-04-02 07:40 UTC, hpaskalev commented on moto/secretsmanager/models.py
> +                secret = self.secrets.get(secret_id)
Sure, I actually used this approach in the beginning but dropped it.

2024-04-02 09:20 UTC, bblommers approved these changes
Great - thank you for adding this to Moto @hpaskalev!

2024-04-02 09:21 UTC, merged