Feature: Bedrock and Bedrock Agents
getmoto/moto pull request #7597
Opened 2024-04-15 16:06 UTC by JoshLevyMN

Support Bedrock and Agents for Bedrock services. 
Includes support for create, delete, list, get, and tagging operations for custom models, model customization jobs, model invocation logging, agents, and knowledge bases.

2024-04-20 19:47 UTC, bblommers requested changes
Hi @JoshLevyMN, thanks for the PR! Please see my comments.

I haven't gone through the tests yet, but I'll do that on a second/third pass.

2024-04-20 19:47 UTC, bblommers commented on moto/bedrock/models.py
> +        self.ModelCustomizationJobs: Dict[str, ModelCustomizationJob] = {}
Variables should all by `snake_case` across both Backends, to keep the style consistent

2024-04-20 19:47 UTC, bblommers commented on moto/bedrock/models.py
> +    def list_model_customization_jobs(
Can we use the existing `@paginator`-decorator here? That way we can avoid all the custom pagination logic.

http://docs.getmoto.org/en/latest/docs/contributing/development_tips/utilities.html#paginator

2024-04-20 19:47 UTC, bblommers commented on moto/bedrockagent/responses.py
> +        # TODO
Nitpick, but it would be good to have this

2024-04-20 19:47 UTC, bblommers commented on moto/bedrockagent/urls.py
> +    # "0/.*$": AgentsforBedrockResponse.dispatch,
These additional URL's don't seem necessary

2024-04-20 19:47 UTC, bblommers commented on moto/bedrockagent/responses.py
> +    # add methods from here
The scaffold script adds them as a pointer/reminder when you start implementing a service, but there's no need to keep them now

2024-04-20 19:47 UTC, bblommers commented on moto/bedrockagent/responses.py
> +# add templates from here
Same here

2024-04-23 14:43 UTC, JoshLevyMN commented
Thanks for the feedback @bblommers, it should all be addressed now. 
All of the testserver tests are failing, and I'm not sure how to fix it.

2024-04-24 21:33 UTC, bblommers commented
Hi @JoshLevyMN, I believe the ServerMode tests are failing because of a bug with how Moto handles request matching. I'll fix that first, and then revisit this. All the changes LGTM btw!

2024-04-27 19:51 UTC, bblommers approved these changes

2024-04-27 19:52 UTC, merged