IoT: Set Certificate ID to SHA256 hexdigest of DER.
getmoto/moto pull request #7865
Opened 2024-07-17 23:08 UTC by mcli

Previous algorithm was based on the PEM format and produced an incorrect certificate ID.
Includes configurable certificate validity for backwards compatibility.

2024-07-17 23:11 UTC, mcli commented
This is an spin of https://github.com/getmoto/moto/pull/6858 which was closed.  Make the default to generate the correct cert ID and allow tests to optionally configure to use previous algorithm which supported invalid certificates in the test.

2024-07-17 23:25 UTC, mcli commented
Fixes https://github.com/getmoto/moto/issues/7866

2024-07-24 20:14 UTC, bblommers requested changes
Hi @mcli, thanks for picking this up. The change makes sense to me - but we would have to keep the current (incorrect) behaviour as the default, and make the DER calculation the opt-in behaviour. We don't want to introduce a breaking change for users.

2024-07-27 15:08 UTC, mcli commented
> Hi @mcli, thanks for picking this up. The change makes sense to me - but we would have to keep the current (incorrect) behaviour as the default, and make the DER calculation the opt-in behaviour. We don't want to introduce a breaking change for users.

Hi @bblommers , Ok.  Set the default to `False`.  Thanks for the comments and I agree with the approach.  Propose to change the default in the next major release.

2024-07-29 19:36 UTC, bblommers approved these changes

2024-07-29 19:36 UTC, merged