CognitoIDP: initiate_auth with USERNAME_PASSWORD_AUTH and SMS MFA
getmoto/moto pull request #7923
Opened 2024-08-02 01:52 UTC by wazy

The initiate_auth call with a AuthFlow of USERNAME_PASSWORD_AUTH was not accounting for SMS MFA and was returning a AuthenticationResult instead of a Challenge as expected.

2024-08-02 19:40 UTC, bblommers requested changes
Hi @wazy, can you extend the test to also `respond_to_auth_challenge`? Just to confirm it is still possible to complete an authentication flow (i.e. get an AccessToken/IdToken) in this scenario.

2024-08-02 21:28 UTC, wazy commented
@bblommers added respond_to_auth_challenge in the test as requested :+1:

2024-08-02 21:43 UTC, wazy commented
@bblommers I noticed that software token mfa was also not being challenged with USER_PASSWORD_AUTH so went and added that code and a test with respond_to_auth_challenge as well.

2024-08-02 22:41 UTC, wazy commented
Fixed test `test_initiate_auth_USER_PASSWORD_AUTH` which had buggy behavior. It should not have any MFA enabled and preferred if it expects AuthenticationResult from initiate_auth and not a challenge.

2024-08-03 08:06 UTC, bblommers approved these changes
Great - thank you for fixing this, and welcome to Moto @wazy!

2024-08-03 08:06 UTC, merged