CloudFormation: create_change_set ChangeSetName more rules
getmoto/moto pull request #7959
Opened 2024-08-09 14:54 UTC by tinngo365

### Pull Request: Refactor Validation in `create_change_set`

**Summary:**

This PR refactors the `create_change_set` function to improve validation by centralizing it in a new `validate_create_change_set` function. This change ensures all parameters are validated consistently and makes it easier to extend validation in the future.

**Changes:**

- **Added `validate_create_change_set` Function**:
  - Centralizes validation for all parameters, currently including `change_set_name` rules (e.g., must start with a letter, be alphanumeric, and under 128 characters).

- **Updated `create_change_set`**:
  - Calls `validate_create_change_set` to validate inputs before processing.

**Benefits:**

- **Improved Maintainability**: Centralized validation simplifies future updates.
- **Enhanced Readability**: Separates validation from core logic.

**Testing:**

- Updated unit tests to cover validation scenarios.
- Confirmed existing functionality remains intact.

[Documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation/client/create_change_set.html#:~:text=A%20change%20set%20name%20can%20contain%20only%20alphanumeric%2C%20case%20sensitive%20characters%2C%20and%20hyphens.%20It%20must%20start%20with%20an%20alphabetical%20character%20and%20can%E2%80%99t%20exceed%20128%20characters.)

![image](https://github.com/user-attachments/assets/c3890eb9-b818-4802-b45d-1c5877c3091f)

2024-08-09 14:55 UTC, tinngo365 commented on tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
> -        ChangeSetName="test_changeset",
Had to change this to follow the new rules

2024-08-09 16:52 UTC, tinngo365 commented
@bblommers could you explain what is wrong?

2024-08-10 13:40 UTC, bblommers requested changes

2024-08-10 13:40 UTC, bblommers commented on moto/cloudformation/utils.py
> +    stack_name: str,
Can we change this here to only include the arguments that we're actually using?
The less arguments, the easier it is to read - and we can always change the signature later

2024-08-10 13:40 UTC, bblommers commented on moto/cloudformation/utils.py
> +) -> Any:
Minor - but we can just simplify this to return `None`

2024-08-10 13:40 UTC, bblommers commented on tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
> +def test_valid_change_set_name():
I don't think this test is necessary? There are other tests that create a changeset, so they verify implicitly that the name is valid

2024-08-10 19:45 UTC, tinngo365 commented
Appreciate the feedback! Thank you

2024-08-11 10:34 UTC, bblommers approved these changes
LGTM - thank you for adding this to Moto @tinngo365!

2024-08-11 10:35 UTC, merged