Verify an expected `UserWarning` from one SQS FIFO queue
getmoto/moto pull request #8041
Opened 2024-08-27 14:37 UTC by kurtmckee

The test suite validates that an SQS FIFO queue with content-deduplication disabled does not receive messages from EventBridge, but doesn't catch and verify the `UserWarning` that gets raised in the code because of this ([recent example in CI](https://github.com/getmoto/moto/actions/runs/10570098846/job/29284013829#step:7:865)).

This PR uses `pytest.warns()` to catch and verify the expected `UserWarning`.

2024-08-30 09:19 UTC, bblommers requested changes
Hi @kurtmckee! Thank you for improving our CI logs.

The tests are run twice - once regular, and once in ServerMode.
Moto in ServerMode runs in separate Docker-container, so we can't intercept any user warnings there.

We could handle this with an if-else (if normal: intercept warning & put_events, else: put_events without intercept). I'm not sure if it's worth the effort though, considering it doesn't improve the readability of the test.

If you can think of a different non-invasive way to achieve this, I'm all ears, but the warnings in the CI don't bother me enough to warrant big changes to the test.

2024-08-30 11:43 UTC, kurtmckee commented
Hello @bblommers, and thanks for the quick review!

The benefit to reducing these warnings is to move toward escalating warnings to errors. It is possible to filter out warnings caused by project dependencies, but it's good hygiene to address (or filter out) existing warnings and then -- from a position of zero warnings -- escalate all warnings to errors. This allows CI to catch new Python `DeprecationWarning`s, or warnings issued by dependencies, early.

It looks like the CI failures are unrelated to this change; were you mentioning the two modes of execution to suggest that this change caused some of the CI failures seen here? Here are the failing tests in CI ([Python 3.12, Ubuntu](https://github.com/getmoto/moto/actions/runs/10580339607/job/29315352846?pr=8041#step:9:1130)):

* `tests/test_core/test_proxy.py::test_http_get_request_can_be_passed_through`
* `tests/test_core/test_proxy.py::test_http_post_request_can_be_passed_through`
* `tests/test_core/test_proxy.py::test_https_request_can_be_passed_through`

but this PR only touched this test:

* `tests/test_events/test_events_integration.py::test_send_to_sqs_fifo_queue`

Looking at the Python 3.12 / Ubuntu CI logs, I'm not seeing that this is related, so please let me know if I'm misunderstanding!

2024-08-30 18:48 UTC, bblommers commented
@kurtmckee Those tests all reach out to website that was temporarily unavailable - that should be fine when restarting the build.  I was talking about these logs:
https://github.com/getmoto/moto/actions/runs/10580339607/job/29315346057

> E           Failed: DID NOT WARN. No warnings of type (<class 'UserWarning'>,) were emitted.
> E            Emitted warnings: [].

2024-08-30 21:16 UTC, kurtmckee commented
Aha, I see now. Thanks for pointing that out!

If you're game for it, lemme see if there's something simple that can be done for this scenario, otherwise you can close this PR. 👍

2024-09-21 10:14 UTC, bblommers approved these changes
LGTM - thank you for fixing this @kurtmckee!

2024-09-21 10:14 UTC, merged