added sagemaker tagging api support
getmoto/moto pull request #8056
Opened 2024-08-29 20:19 UTC by jamarcelin

2024-08-31 09:41 UTC, bblommers requested changes
Hi @jamarcelin! It looks like a test is now failing as well: https://github.com/getmoto/moto/actions/runs/10622064984/job/29445807888?pr=8056

2024-08-31 09:41 UTC, bblommers commented on moto/sagemaker/models.py
> +        self.arn = self.pipeline_execution_arn
I realize that it's quite a lot of work to rewrite these - but I think we should all settle on `self.arn`, and get rid of the `self.pipeline_execution_arn`. Having two properties to point to the same value is going to be confusing, and can lead to drift.

(Same for all the other models..)

2024-09-03 18:38 UTC, jamarcelin commented
Hey @bblommers, the services have all been updated to only use `self.arn`. Thanks!

2024-09-04 07:43 UTC, bblommers approved these changes
Great - thank you @jamarcelin!

2024-09-04 07:43 UTC, merged

2025-05-07 20:27 UTC, srausser commented
@bblommers it looks like you missed the transform job adding the arn back to the payload
`response["TransformJobArn"] = response.pop("Arn")`

or am i missing something

2025-05-10 12:25 UTC, bblommers commented
Good catch @srausser - I've raised https://github.com/getmoto/moto/pull/8886 so we now return the TransformJobArn