implement CopyTags and Tags parameters for RDS copy_db_snapshot()
getmoto/moto pull request #8320
Opened 2024-11-15 16:26 UTC by snordhausen

Testing on AWS showed that tags are never merged. Instead, AWS uses either the provided *Tags* value or the tags of the original snapshot.
Also, the old code always copied the tags of the source snapshots, but *CopyTags* actually defaults to False.

I'll apply the same change to copy_db_**cluster**_snapshot once this PR is merged. It behaves in the same way as copy_db_snapshot with regards to tags.

2024-11-16 13:32 UTC, bblommers requested changes

2024-11-16 13:32 UTC, bblommers commented on tests/test_rds/test_rds.py
> +    kwargs_and_expected_results = [
Nice! This is a very clean and clear way of showing the different behaviours.

Just one nitpick - can you use this list to parametrize the entire test? That is going to include a bit of overhead, but having separate tests for each use case makes debugging later on much easier (IMHO).

So the resulting test signature would look something like this:
```
@pytest.mark.parametrize("kwargs,expected_result", [..])
def test_copy_db_snapshots_copytags_and_tags(kwargs, expected_result):
    ...
```

2024-11-20 17:20 UTC, snordhausen commented
@bblommers I'll take at this eventually, just didn't have time yet.

2024-12-05 20:47 UTC, bblommers approved these changes
This looks great - thank you for fixing this in Moto @snordhausen!

2024-12-05 20:47 UTC, merged