RDS: allow snapshot ARNs for copy and restore
getmoto/moto pull request #8372
Opened 2024-12-06 13:23 UTC by snordhausen

`copy_db_snapshot()` and `restore_db_instance_from_db_snapshot()` should accept both names and full ARNs as snapshot identifier. For copy_db_snapshot(), only the SourceDBSnapshotIdentifier can be an ARN, the TargetDBSnapshotIdentifier has to be a name.

2024-12-06 14:31 UTC, snordhausen commented on moto/rds/models.py
> +            )
Looking into the test coverage...

2024-12-06 22:27 UTC, bpandola requested changes

2024-12-06 22:27 UTC, bpandola commented on moto/rds/models.py
> +            )
Raising `NotImplementedError` here would be more appropriate, since this is not an AWS error but  internal to moto.

2024-12-06 22:27 UTC, bpandola commented on tests/test_rds/test_rds.py
> +    assert "not yet implemented in moto" in ex.value.response["Error"]["Message"]
No need to cover something that's not implemented.  And, per my previous comment, if you raise `NotImplementedError` CodeCov will ignore that line in the coverage calculation.

2024-12-11 11:42 UTC, snordhausen commented
@bpandola I fixed it as recommended by you. Please review again.

2024-12-11 21:52 UTC, bpandola approved these changes
Thanks @snordhausen

2024-12-11 21:52 UTC, merged