Kafka V1 Support
getmoto/moto pull request #8381
Opened 2024-12-08 00:46 UTC by jamarcelin

2024-12-08 00:50 UTC, jamarcelin commented
@bblommers I am having some issue with some of the endpoints. On line 147 of moto/kafka/responses.py, it is correctly printing (and returning) the response but the response isn't correct in the tests. I think it's a URL issues but not sure.

2024-12-08 11:14 UTC, bblommers commented
Hi @jamarcelin! It looks like some of the response-keys simply need to be lowercased. For example:

```diff
diff --git a/moto/kafka/models.py b/moto/kafka/models.py
index 5cd36741d..e2973d5f8 100644
--- a/moto/kafka/models.py
+++ b/moto/kafka/models.py
@@ -231,11 +231,11 @@ class KafkaBackend(BaseBackend):
     ):
         cluster_info_list = [
             {
-                "ClusterArn": cluster.arn,
-                "ClusterName": cluster.cluster_name,
-                "ClusterType": cluster.cluster_type,
-                "State": cluster.state,
-                "CreationTime": cluster.creation_time,
+                "clusterArn": cluster.arn,
+                "clusterName": cluster.cluster_name,
+                "clusterType": cluster.cluster_type,
+                "state": cluster.state,
+                "creationTime": cluster.creation_time,
             }
             for cluster in self.clusters.values()
         ]
```

That change ensures that the `list_clusters_v2()`-method call succeeds in the `test_create_cluster_v2()`. I imagine that the other failures/tests have similar problems/solutions, but I haven't tested that.

This is the first thing I tried, and it happened to work - just because I have run into this problem in the past. The botocore spec is always good place to confirm things like this though, as you can see that they lowercase all `locationName`'s:

https://github.com/boto/botocore/blob/cacd0e9fdba71d1f976069a072576ad74b888bea/botocore/data/kafka/2018-11-14/service-2.json#L2429

2024-12-09 04:53 UTC, jamarcelin commented
@bblommers Gotcha, thanks for the help! I fixed the tests and made some changes. The linter is having an issue with broker_node_group_info from FakeKafkaCluster. Any idea how to resolve this?

2024-12-09 19:40 UTC, bblommers commented
Hi @jamarcelin! You can run `ruff format moto/kafka` to fix that. I've pushed a fix for now + some typing fixes - I'll leave the test failures to you :slightly_smiling_face:

2024-12-09 23:10 UTC, jamarcelin commented
@bblommers Test should be fixed now, just waiting on check to complete. Thanks again!

2024-12-10 04:17 UTC, jamarcelin commented
@bblommers Hey, sorry to keep pinging, it seems the tests are failing in server mode? Is this caused by an issue with the urls?

2024-12-10 10:20 UTC, bpandola commented
@jamarcelin I pushed a commit to fix the urls.  They have ARNs in them, which contain forward slashes.

2024-12-10 13:54 UTC, jamarcelin commented
@bblommers Awesome! Thanks for the help! This looks good to merge to me. Also, is there a specific cadence for releases? Or is there anyway to trigger a release?

2024-12-11 02:34 UTC, bpandola requested changes
Can you add tests to cover the lines flagged by Codecov?  It's unclear, for example, whether or not `FakeKafkaCluster.to_dict()` is unreachable code or just not covered by tests.

2024-12-12 19:02 UTC, bblommers commented on moto/kafka/models.py
> +    def to_dict(self) -> Dict[str, Any]:
Can we not remove this method altogether @jamarcelin? As far as I can tell, it's not used anywhere

2024-12-12 19:03 UTC, bblommers commented
> Also, is there a specific cadence for releases? Or is there anyway to trigger a release?

I try to do them every two weeks - the next one should come this weekend. :slightly_smiling_face:

2024-12-13 20:55 UTC, bblommers approved these changes
Great - thank you @jamarcelin!

2024-12-13 20:55 UTC, merged